# .pre-commit-config.yaml
# This file configures the pre-commit hooks that will be run before each push.
# See https://pre-commit.com for more information.
# See https://pre-commit.com/hooks.html for more hooks.

# To use these hooks:
# 1. Install pre-commit (https://pre-commit.com/#install).
#    In most cases, this will involve running `pip install pre-commit`.
# 2. In your terminal, navigate to your repository and run `pre-commit install`.
#    This will install the hooks.
# 3. Now, the hooks will automatically run every time you try to push.
#    If formatting is needed, the push will be blocked with instructions to format first.
# 4. If you want to manually run all hooks on all files, run `pre-commit run --all-files`.
# 5. To update to the latest versions of the hooks, run `pre-commit autoupdate`.

# Stop on first failure for clear error reporting
fail_fast: true

repos:
  - repo: local
    hooks:
      - id: ruff-check
        name: Check code style with Ruff
        entry: python -m ruff check --config=.ruff.toml
        language: system
        stages: [pre-push]
        types: [python]
        pass_filenames: false
        
      - id: ruff-format-check
        name: Check code formatting with Ruff
        entry: python -m ruff format --check --config=.ruff.toml
        language: system
        stages: [pre-push]
        types: [python]
        pass_filenames: false
        
      - id: mypy
        name: Type checking with MyPy
        entry: python -m mypy app src
        language: system
        stages: [pre-push]
        types: [python]
        pass_filenames: false
        
      - id: tests
        name: Run unit tests
        entry: python run_enhanced_tests.py
        language: system
        stages: [pre-push]
        pass_filenames: false