# .pre-commit-config.yaml
# This file configures the pre-commit hooks that will be run before each push.
# See https://pre-commit.com for more information.
# See https://pre-commit.com/hooks.html for more hooks.

# To use these hooks:
# 1. Install pre-commit (https://pre-commit.com/#install).
#    In most cases, this will involve running `pip install pre-commit`.
# 2. In your terminal, navigate to your repository and run `pre-commit install`.
#    This will install the hooks.
# 3. Now, just run `git push` - the hook will automatically:
#    - Apply all code formatting and style fixes
#    - Commit those fixes automatically  
#    - Run all quality checks (ruff, mypy, tests)
#    - Push everything if all checks pass
# 4. If you want to manually run all hooks on all files, run `pre-commit run --all-files`.
# 5. To update to the latest versions of the hooks, run `pre-commit autoupdate`.

# Stop on first failure for clear error reporting
fail_fast: true

repos:
  - repo: local
    hooks:
      - id: smart-auto-fix-and-validate
        name: Auto-fix code and validate quality
        entry: python scripts/smart_auto_fix_and_validate.py
        language: system
        stages: [pre-push]
        pass_filenames: false
        verbose: true
        always_run: true