# .pre-commit-config.yaml
# This file configures the pre-commit hooks that will be run before each push.
# See https://pre-commit.com for more information.
# See https://pre-commit.com/hooks.html for more hooks.

# To use these hooks:
# 1. Install pre-commit (https://pre-commit.com/#install).
#    In most cases, this will involve running `pip install pre-commit`.
# 2. In your terminal, navigate to your repository and run `pre-commit install`.
#    This will install the hooks.
# 3. Now, the hooks will automatically run every time you try to push.
#    The auto-fix hook will apply formatting and style fixes, commit them, and push when all checks pass.
# 4. If you want to manually run all hooks on all files, run `pre-commit run --all-files`.
# 5. To update to the latest versions of the hooks, run `pre-commit autoupdate`.

# Stop on first failure since we want the auto-fix process to handle everything
fail_fast: true

repos:
  - repo: local
    hooks:
      - id: auto-fix-and-push
        name: Auto-fix code quality issues and push
        entry: python scripts/auto_fix_and_push.py
        language: system
        stages: [pre-push]
        pass_filenames: false
        verbose: true
        always_run: true