# Specify the app type
app_type = "tree"

# Specify the Python version
python_version = "3.12"

# This should match the name of your app on the VIKTOR platform
registered_name = "automatisch-toetsmodel-plaatbruggen" 