name: Continuous Integration

on:
  pull_request:
    branches: [ development, main ]
  push:
    branches: [ development, main ]

jobs:
  code-quality:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements_dev.txt

      - name: Run Ruff code style check
        run: python scripts/run_ruff_check.py

      - name: Run Ruff code formatter check
        run: python scripts/run_ruff_format.py

      - name: Run MyPy type checking
        run: python scripts/run_mypy.py

      - name: Run unit tests
        run: python run_enhanced_tests.py 